# Generated by Django 2.2.1 on 2019-05-18 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('goal', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('start_date', models.DateField(default=datetime.datetime(2019, 5, 18, 1, 21, 20, 404315))),
            ],
        ),
    ]
